### ISSUE TITLE
Error Running Script

### ISSUE THREAD

**Issue by gedeagas** [drejkim/face-detection-node-opencv#11]
Agastya-Darma-MacBook-Pro:server gedeagas$ node server.js 
module.js:327
    throw err;
    ^

Error: Cannot find module 'opencv'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/gedeagas/Make/face-detection-node-opencv/server/lib/routes/socket.js:1:72)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
Agastya-Darma-MacBook-Pro:server gedeagas$

**Comment by gedeagas** [comment]
node-opencv error ( mac only )
https://github.com/peterbraden/node-opencv/issues/441#issuecomment-246333127
