### ISSUE TITLE
Can't install OpenCV

### ISSUE THREAD

**Issue by yiulix** [drejkim/face-detection-node-opencv#12]
C:\Users\Administrator\Downloads\face-detection-node-opencv-master\face-detectio
n-node-opencv-master\server>npm install
npm WARN installMany node-pre-gyp was bundled with opencv@5.0.0, but bundled pac
kage wasn't found in unpacked tree
\

> opencv@5.0.0 install C:\Users\Administrator\Downloads\face-detection-node-open
> cv-master\face-detection-node-opencv-master\server\node_modules\opencv
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-opencv.s3.amazonaws.com/opencv
/v5.0.0/Release/node-v46-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for opencv@5.0.0 and node@4.5.0 (
node-v46 ABI) (falling back to source compile with node-gyp)

C:\Users\Administrator\Downloads\face-detection-node-opencv-master\face-detectio
n-node-opencv-master\server\node_modules\opencv>if not defined npm_config_node_g
yp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_
modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

C:\Users\Administrator\Downloads\face-detection-node-opencv-master\face-detectio
n-node-opencv-master\server\node_modules\opencv>if not defined npm_config_node_g
yp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_
modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\User
s\Administrator\Downloads\face-detection-node-opencv-master\face-detection-node-
opencv-master\server\node_modules\opencv\build\opencv\v5.0.0\Release\node-v46-wi
n32-x64\opencv.node --module_name=opencv --module_path=C:\Users\Administrator\Do
wnloads\face-detection-node-opencv-master\face-detection-node-opencv-master\serv
er\node_modules\opencv\build\opencv\v5.0.0\Release\node-v46-win32-x64 )  else (n
ode "" configure --fallback-to-build --module=C:\Users\Administrator\Downloads\f
ace-detection-node-opencv-master\face-detection-node-opencv-master\server\node_m
odules\opencv\build\opencv\v5.0.0\Release\node-v46-win32-x64\opencv.node --modul
e_name=opencv --module_path=C:\Users\Administrator\Downloads\face-detection-node
-opencv-master\face-detection-node-opencv-master\server\node_modules\opencv\buil
d\opencv\v5.0.0\Release\node-v46-win32-x64 )
C:\Users\Administrator\Downloads\face-detection-node-opencv-master\face-detectio
n-node-opencv-master\server\node_modules\opencv\utils\find-opencv.js:39
            throw new Error("ERROR: OPENCV_DIR doesn't seem to be defined");
            ^

Error: ERROR: OPENCV_DIR doesn't seem to be defined
    at C:\Users\Administrator\Downloads\face-detection-node-opencv-master\face-d
etection-node-opencv-master\server\node_modules\opencv\utils\find-opencv.js:39:1
9
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
gyp: Call to 'node utils/find-opencv.js --libs' returned exit status 1 while in
binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_module
s\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodej
s\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "configure" "--f
allback-to-build" "--module=C:\Users\Administrator\Downloads\face-detection-
node-opencv-master\face-detection-node-opencv-master\server\node_modules\ope
ncv\build\opencv\v5.0.0\Release\node-v46-win32-x64\opencv.node" "--module_
name=opencv" "--module_path=C:\Users\Administrator\Downloads\face-detection-
node-opencv-master\face-detection-node-opencv-master\server\node_modules\ope
ncv\build\opencv\v5.0.0\Release\node-v46-win32-x64"
gyp ERR! cwd C:\Users\Administrator\Downloads\face-detection-node-opencv-master\
face-detection-node-opencv-master\server\node_modules\opencv
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallb
ack-to-build --module=C:\Users\Administrator\Downloads\face-detection-node-openc
v-master\face-detection-node-opencv-master\server\node_modules\opencv\build\open
cv\v5.0.0\Release\node-v46-win32-x64\opencv.node --module_name=opencv --module_p
ath=C:\Users\Administrator\Downloads\face-detection-node-opencv-master\face-dete
ction-node-opencv-master\server\node_modules\opencv\build\opencv\v5.0.0\Release\
node-v46-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Administrator\
Downloads\face-detection-node-opencv-master\face-detection-node-opencv-master\se
rver\node_modules\opencv\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:829:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\Admi
nistrator\Downloads\face-detection-node-opencv-master\face-detection-node-ope
ncv-master\server\node_modules\opencv\node_modules\node-pre-gyp\bin\node-
pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Administrator\Downloads\face-detection-node-openc
v-master\face-detection-node-opencv-master\server\node_modules\opencv
node-pre-gyp ERR! node -v v4.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\
Administrator\Downloads\face-detection-node-opencv-master\face-detection-node-op
encv-master\server\node_modules\opencv\build\opencv\v5.0.0\Release\node-v46-win3
2-x64\opencv.node --module_name=opencv --module_path=C:\Users\Administrator\Down
loads\face-detection-node-opencv-master\face-detection-node-opencv-master\server
\node_modules\opencv\build\opencv\v5.0.0\Release\node-v46-win32-x64' (1)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! opencv@5.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@5.0.0 install script 'node-pre-gyp install --fallb
ack-to-build'.
npm ERR! This is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs opencv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\Downloads\face-detection-node-opencv-master\
face-detection-node-opencv-master\server\npm-debug.log

C:\Users\Administrator\Downloads\face-detection-node-opencv-master\face-detectio
n-node-opencv-master\server>

**Comment by yiulix** [comment]
About is the error code. I have installed OpenCV 2.4.13 and set the environment variable OPENCV_DIR as well as added it to the system path. Can anyone help me with it ?

**Comment by estherjk** [comment]
Hmm, unsure what the issue is. Can you check https://github.com/peterbraden/node-opencv/issues? It looks like people have had issues installing node-opencv. Hopefully, you will find something helpful while perusing through the list of issues....

**Comment by BonsoirDiep** [comment]
https://github.com/bengfarrell/installing-node-opencv

node-opencv for OpenCv 2.4.9
You can see file .pc in "node-opencv\utils", where config not correct for you...
Need reconfig and build package. Good luck!

**Comment by oriolpuig** [comment]
Check those steps: https://github.com/peterbraden/node-opencv/issues/378#issuecomment-254715793

Good luck!

**Comment by strarsis** [comment]
On Ubuntu/Debian installing the `libopencv-dev` package solved the issue for me.
