### ISSUE TITLE
Error: Cannot find module './lib/config/server'

### ISSUE THREAD

**Issue by ZacharAdn** [drejkim/face-detection-node-opencv#15]
got this error when I'm run
>$ node server.js 

>module.js:472
    throw err;
    ^
Error:
 Cannot find module './lib/config/server'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/zahar/workplace/openCV/node/face-detection-node-opencv/server/server.js:7:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by estherjk** [comment]
Did you receive any errors when running `npm install`?
