### ISSUE TITLE
[RPI2B] Camera could not be opened

### ISSUE THREAD

**Issue by Francescu** [drejkim/face-detection-node-opencv#3]
When I launch `sudo node server.js` on my Raspberry Pi 2 B, I got an error:

```
socket.js:14
var camera = new cv.VideoCapture(0);
             ^
Error: Camera could not be opened
    at Error (native)
    at Object.<anonymous> (/home/x/face-detection-node-opencv/server/lib/routes/socket.js:14:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/x/face-detection-node-opencv/server/server.js:26:21)
    at Module._compile (module.js:460:26)
```

I tried with both open-cv 2.4.1 compiled on the RPI and installed from apt-get.

Any idea?

**Comment by estherjk** [comment]
Unfortunately, OpenCV 2.4.1 has not worked for others... see https://github.com/peterbraden/node-opencv/issues/176. Can you try installing 2.4.9 or higher (but not 3.x)?

**Comment by Wepamat** [comment]
Hey drejkim,

unfortunately I do have the same Issue with my Raspberry 3 on OpenCV 2.4.13 and Node.js 0.12.15. I compiled OpenCV on the Raspberry (no errors). Also the npm install did work out fine ..
Any Ideas?

**Comment by Wepamat** [comment]
Solved it actually. Another Process (Service) of mine was keeping the camera busy.
