### ISSUE TITLE
server.js doesnt run

### ISSUE THREAD

**Issue by zshn25** [drejkim/face-detection-node-opencv#9]
I did npm install and it installed sucessfully.
`npm WARN installMany node-pre-gyp was bundled with opencv@5.0.0, but bundled package wasn't found in unpacked tree
\

> opencv@5.0.0 install /home/zee/face-detection-node-opencv/server/node_modules/opencv
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-opencv.s3.amazonaws.com/opencv/v5.0.0/Release/node-v46-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for opencv@5.0.0 and node@4.4.7 (node-v46 ABI) (falling back to source compile with node-gyp) 
make: Entering directory `/home/zee/face-detection-node-opencv/server/node_modules/opencv/build'
  CXX(target) Release/obj.target/opencv/src/init.o
  CXX(target) Release/obj.target/opencv/src/Matrix.o
  CXX(target) Release/obj.target/opencv/src/OpenCV.o
  CXX(target) Release/obj.target/opencv/src/CascadeClassifierWrap.o
  CXX(target) Release/obj.target/opencv/src/Contours.o
  CXX(target) Release/obj.target/opencv/src/Point.o
  CXX(target) Release/obj.target/opencv/src/VideoCaptureWrap.o
  CXX(target) Release/obj.target/opencv/src/CamShift.o
  CXX(target) Release/obj.target/opencv/src/HighGUI.o
  CXX(target) Release/obj.target/opencv/src/FaceRecognizer.o
  CXX(target) Release/obj.target/opencv/src/Features2d.o
  CXX(target) Release/obj.target/opencv/src/BackgroundSubtractor.o
  CXX(target) Release/obj.target/opencv/src/Constants.o
  CXX(target) Release/obj.target/opencv/src/Calib3D.o
  CXX(target) Release/obj.target/opencv/src/ImgProc.o
  CXX(target) Release/obj.target/opencv/src/Stereo.o
  CXX(target) Release/obj.target/opencv/src/LDAWrap.o
  SOLINK_MODULE(target) Release/obj.target/opencv.node
  COPY Release/opencv.node
  COPY /home/zee/face-detection-node-opencv/server/node_modules/opencv/build/opencv/v5.0.0/Release/node-v46-linux-x64/opencv.node
  TOUCH Release/obj.target/action_after_build.stamp
  CXX(target) Release/obj.target/test_nativemat/test/nativemat.o
  SOLINK_MODULE(target) Release/obj.target/test_nativemat.node
  COPY Release/test_nativemat.node
make: Leaving directory`/home/zee/face-detection-node-opencv/server/node_modules/opencv/build'
opencv@5.0.0 node_modules/opencv
├── buffers@0.1.1
├── nan@2.3.5
└── node-pre-gyp@0.6.29 (semver@5.2.0, nopt@3.0.6, mkdirp@0.5.1, rc@1.1.6, tar@2.2.1, rimraf@2.5.2, npmlog@3.1.2, tar-pack@3.1.4, request@2.72.0)`

When I run node server.js it gives me the following error
`events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:873:11)
    at exports._exceptionWithHostPort (util.js:896:20)
    at Server._listen2 (net.js:1250:14)
    at listen (net.js:1286:10)
    at Server.listen (net.js:1382:5)
    at Object.<anonymous> (/home/zee/face-detection-node-opencv/server/server.js:20:8)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
`

**Comment by zshn25** [comment]
It was the issue with my port. I changed to some other port and it worked.
